language: cpp
branches:
    # We need to whitelist the branches which we want to have "push" automation.
    # Pull request automation is not constrained to this set of branches.
    only:
        - master
matrix:
    include:
        - os: linux
          dist: trusty
          sudo: required
          node_js:
              - "8"
          env:
              - EVM2WASM=0
        - os: linux
          dist: trusty
          sudo: required
          node_js:
              - "8"
          env:
              - EVM2WASM=1
git:
    depth: 2
script:
    - mkdir build && cd build
    - cmake -DEVM2WASM=$EVM2WASM ..
    - cmake --build . -- -j4
